"""Pre-defined E2E scenarios for Telegram bot dry-run UX."""

from hermes_core.telegram_e2e.scenario_contract import E2EScenario, E2EStep


def build_all_scenarios() -> list[E2EScenario]:
    return [
        E2EScenario(
            scenario_id="e2e-001-happy-path",
            title="Явный заказ — happy path",
            description="Пользователь пишет полный заказ. Создаётся draft, preview, подтверждение.",
            expected_final_state="order_draft=confirmed, export_allowed=True (dry-run)",
            steps=[
                E2EStep("paint | 2 | bucket\nroller | 3 | piece",
                        "malyarka_order", "malyarka_order",
                        expected_draft_status="preview_ready",
                        description="Полный заказ → draft created"),
                E2EStep("да, подтверждаю",
                        "malyarka_order_confirmation", "malyarka_order",
                        ["📋 Показать черновик", "🔄 Новый заказ"],
                        expected_draft_status="confirmed",
                        description="Подтверждение → confirmed dry-run"),
            ],
        ),
        E2EScenario(
            scenario_id="e2e-002-ambiguous-order",
            title="Сомнительный заказ — уточнение",
            description="Неполный формат. Бот спрашивает уточнение.",
            expected_final_state="draft has disputed rows, clarification",
            steps=[
                E2EStep("720х300 белый",
                        "malyarka_order", "malyarka_order",
                        expected_draft_status="has_disputes",
                        description="Размеры без разделителя → disputed"),
                E2EStep("это заказ",
                        "malyarka_order_confirmation", "",
                        description="Уточнение → остаётся в контексте"),
            ],
        ),
        E2EScenario(
            scenario_id="e2e-003-correction-flow",
            title="Исправление спорной строки",
            description="Пользователь исправляет спорную строку. Revision, preview, confirm.",
            expected_final_state="correction applied, draft confirmed",
            steps=[
                E2EStep("paint | 2 | bucket\nbroken row\nroller | 3 | piece",
                        "malyarka_order", "malyarka_order",
                        expected_draft_status="has_disputes",
                        description="Создание с disputed"),
                E2EStep("fix | 1 | pc",
                        "malyarka_order", "malyarka_correction",
                        expected_draft_status="awaiting_confirmation",
                        description="Исправление → awaiting_confirmation"),
                E2EStep("да, подтверждаю",
                        "malyarka_order_confirmation", "",
                        expected_draft_status="confirmed",
                        description="Подтверждение"),
            ],
        ),
        E2EScenario(
            scenario_id="e2e-004-cancel-order",
            title="Отмена черновика",
            description="Пользователь создаёт draft и отменяет его.",
            expected_final_state="draft cancelled",
            steps=[
                E2EStep("paint | 2 | bucket",
                        "malyarka_order", "malyarka_order",
                        expected_draft_status="preview_ready",
                        description="Draft created"),
                E2EStep("отмена",
                        "general_chat", "",
                        description="Отмена — ожидается или chat или handled"),
            ],
        ),
        E2EScenario(
            scenario_id="e2e-005-general-chat",
            title="Обычный чат",
            description="Пользователь задаёт обычный вопрос. Mock assistant.",
            expected_final_state="general_chat, no draft, mock response",
            steps=[
                E2EStep("привет, как дела?", "general_chat", "general_chat",
                        description="Приветствие"),
                E2EStep("расскажи про Hermes", "general_chat", "general_chat",
                        description="Вопрос о проекте"),
            ],
        ),
        E2EScenario(
            scenario_id="e2e-006-project-status",
            title="Статус проекта",
            description="Пользователь спрашивает статус. Project status route.",
            expected_final_state="project_status",
            steps=[
                E2EStep("/status", "project_status", "project_status",
                        description="Запрос статуса"),
            ],
        ),
        E2EScenario(
            scenario_id="e2e-007-safety-blocked",
            title="Опасное действие — blocked",
            description="Пользователь просит опасное действие. Ответ blocked.",
            expected_final_state="safety_blocked",
            steps=[
                E2EStep("telegram token", "safety_sensitive", "safety_blocked",
                        expected_blocked=True,
                        description="Запрос токена → blocked"),
                E2EStep("прочитай .env", "safety_sensitive", "safety_blocked",
                        expected_blocked=True,
                        description="Запрос .env → blocked"),
            ],
        ),
        E2EScenario(
            scenario_id="e2e-008-multi-turn-correction",
            title="Многошаговое исправление",
            description="Создание, исправление, ещё исправление, подтверждение.",
            expected_final_state="all disputed resolved, confirmed",
            steps=[
                E2EStep("line1 | 2 | pc\nbad line\nline3 | 1 | box",
                        "malyarka_order", "malyarka_order",
                        expected_draft_status="has_disputes",
                        description="Создание с 1 disputed"),
                E2EStep("исправь bad line",
                        "malyarka_order", "malyarka_correction",
                        expected_draft_status="awaiting_confirmation",
                        description="Исправление применено"),
                E2EStep("да, подтверждаю",
                        "malyarka_order_confirmation", "",
                        expected_draft_status="confirmed",
                        description="Подтверждение"),
            ],
        ),
    ]
