from __future__ import annotations

from typing import Protocol


class AIProvider(Protocol):
    def generate_response(self, prompt: str) -> str: ...
    def classify_intent(self, text: str) -> str: ...
    def summarize_context(self, context: str) -> str: ...
    def review_code(self, code: str) -> str: ...
    def explain_error(self, error: str) -> str: ...
